# set up tomcat consistently whenever needed.  Used as:
# - include: ../common/tasks/tomcat.yml 
# "tomcat" variable controls version (@see common/vars)
- include: ../../common/tasks/setfacts.yml 

- name: install libtcnative-1 (RedHat)
  yum: pkg={{libtcnative}} state=present
  tags:
    - packages 
  when: ansible_os_family == "RedHat" and tomcat_apr == true
  tags:
    - tomcat

- name: install tomcat (RedHat)
  yum: name={{tomcat}} state=present
  tags:
    - packages 
  notify: 
    - restart tomcat
  when: ansible_os_family == "RedHat"
  tags:
    - tomcat

- name: install libtcnative-1 (Debian)
  apt: pkg={{libtcnative}} state=present update_cache=yes
  tags:
    - packages 
  when: ansible_os_family == "Debian" and tomcat_apr == true
  tags:
    - tomcat

- name: install tomcat (Debian)
  apt: pkg={{tomcat}} state=present update_cache=yes
  tags:
    - packages 
  when: ansible_os_family == "Debian"
  tags:
    - tomcat

- name: setup tomcat
  template: src={{ item }} dest={{ tomcat_conf_dir }}/server.xml owner={{ tomcat_user }} mode=0644 backup=true
  with_first_found:
    - "../templates/server.xml.{{ ansible_distribution }}-{{ ansible_distribution_version }}.j2"
    - "../templates/server.xml.{{ ansible_distribution }}.j2"
    - "../templates/server.xml.{{ ansible_os_family }}.j2"
    - "../templates/server.xml.j2"
  notify: 
    - restart tomcat

- name: enable proxy_ajp
  apache2_module: state=present name=proxy_ajp
  when: ansible_os_family == "Debian" and tomcat_ajp == true # already on RedHat
  notify: 
    - restart apache
  tags:
    - tomcat

# replace the commented out java_opts that ships with the CentOS install which is:
# JAVA_OPTS="-Xminf0.1 -Xmaxf0.3"        
- name: configure tomcat memory (RedHat)
  lineinfile: 
    dest={{tomcat_conf}}
    regexp="-Djava.awt.headless=true -Xmx128m"
    line='JAVA_OPTS="{{tomcat_java_opts}}"'
  notify: 
    - restart tomcat
  when: ansible_os_family == "RedHat"
  tags:
    - tomcat

- name: configure tomcat memory (Debian)
  lineinfile: 
    dest={{tomcat_conf}}
    regexp="-Xminf0.1 -Xmaxf0.3"
    line='JAVA_OPTS="{{tomcat_java_opts}}"'
  notify: 
    - restart tomcat
  when: ansible_os_family == "Debian"
  tags:
    - tomcat

- name: Set JAVA_HOME  (Debian)
  lineinfile: " 
    dest={{tomcat_conf}}
    regexp=^JAVA_HOME
    line='JAVA_HOME=/usr/lib/jvm/java-7-oracle'"
  notify: 
    - restart tomcat    
  when: ansible_os_family == "Debian"
  tags:
    - tomcat