- include: ../../common/tasks/setfacts.yml
  tags:
    - volunteer-portal

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/volunteer-portal/config"
  tags:
    - volunteer-portal

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}}  group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/volunteer-portal/project"
    - "{{data_dir}}/volunteer-portal/projectStaging"
    - "{{data_dir}}/volunteer-portal/projectType"
  tags:
    - volunteer-portal

- name: set data ownership
  file: path={{data_dir}}/volunteer-portal owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  tags:
    - volunteer-portal

- name: copy all config.properties
  template: src=config.properties.j2 dest={{data_dir}}/volunteer-portal/config/volunteer-portal-config.properties
  tags:
    - volunteer-portal

- name: Copy proxy config to conf.d (Redhat)
  template: src=volunteer-portal.j2 dest=/etc/httpd/conf.d/default-vhost.conf
  when: ansible_os_family == "RedHat" 
  tags:
    - volunteer-portal

- name: Create Volunteer Portal virtual host config file (Debian)
  template: src=volunteer-portal.j2 dest=/etc/apache2/sites-available/volunteer-portal owner=root group=root
  when: ansible_os_family == "Debian" 
  tags:
    - volunteer-portal

- name: Disable all existing virtual hosts (TODO don't do this) (Debian)
  command: "a2dissite *" 
  ignore_errors: yes
  when: ansible_os_family == "Debian" 
  tags:
    - volunteer-portal

- name: Enable VP virtual host (Debian)
  command: "a2ensite volunteer-portal" 
  ignore_errors: yes
  when: ansible_os_family == "Debian" 
  notify:
    - reload apache
  tags:
    - volunteer-portal

- name: Ensure volunteers WWW directory exists
  file: path={{ item }} state=directory
  with_items:
    - /srv/volunteer/www
    - /srv/volunteer/www/data
  tags:
    - volunteer-portal

- name: Symlink data dir to /data
  file: dest=/srv/volunteer/www/data/volunteer src={{data_dir}}/volunteer-portal state=link
  tags:
    - volunteer-portal

- name: download from maven repo
  get_url: url={{ volunteers_url }} dest="{{tomcat_webapps}}ROOT.war"
  notify:
    - restart tomcat
  tags:
    - volunteer-portal
